---
- name: Copy new files and directories
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ item }}"
  loop:
    - ".config"
    - ".face"
    - ".gitconfig"
    - ".gtkrc-2.0"
    - ".local"
    - ".ssh"
    - "scripts"

- name: Copy new files and directories (root)
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "~/{{ item }}"
  loop:
    - "etc"
  become: true

- name: Symlink xdg environment variables
  ansible.builtin.file:
    src: "~/.config/user-dirs.dirs"
    dest: "~/.config/environment.d/user-dirs.dirs.conf"
    state: "link"

- name: Download bash cat
  ansible.builtin.git:
    repo: https://github.com/exu-g/bash-cat-with-cat.git
    dest: "/tmp/bash-cat-with-cat"

- name: Copy bash cat to scripts
  ansible.builtin.copy:
    src: "/tmp/bash-cat-with-cat/cat.sh"
    dest: "~/scripts/pieces/cat.sh"
    mode: "0755"

- name: Reload user systemd services
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable fstrim
  ansible.builtin.systemd_service:
    name: fstrim.timer
    state: "started"
    enabled: true
  become: true

- name: Enable NTP
  ansible.builtin.command: timedatectl set-ntp true
  become: true

- name: Enable ssh-agent
  ansible.builtin.systemd_service:
    name: ssh-agent
    state: "restarted"
    enabled: true

- name: Enable vnstat
  ansible.builtin.systemd_service:
    name: vnstat
    state: "started"
    enabled: true
  become: true
